insert into career(career_name) value ('신입');
insert into career(career_name) value ('주니어(1~3)');
insert into career(career_name) value ('미들(5~8)');
insert into career(career_name) value ('시니어(9~12)');
insert into career(career_name) value ('엑스퍼트(13이상)');

insert into skill(skill_name) value ('Java');
insert into skill(skill_name) value ('React');
INSERT INTO skill(skill_name) VALUES ('Python');
INSERT INTO skill(skill_name) VALUES ('JavaScript');
INSERT INTO skill(skill_name) VALUES ('Spring');
INSERT INTO skill(skill_name) VALUES ('NodeJs');
INSERT INTO skill(skill_name) VALUES ('C#');
INSERT INTO skill(skill_name) VALUES ('Vue.js');
INSERT INTO skill(skill_name) VALUES ('Ruby');
INSERT INTO skill(skill_name) VALUES ('Swift');
INSERT INTO skill(skill_name) VALUES ('HTML');
INSERT INTO skill(skill_name) VALUES ('CSS');
INSERT INTO skill(skill_name) VALUES ('SQL');
INSERT INTO skill(skill_name) VALUES ('Angular');
INSERT INTO skill(skill_name) VALUES ('PHP');
INSERT INTO skill(skill_name) VALUES ('Kotlin');
INSERT INTO skill(skill_name) VALUES ('Docker');
INSERT INTO skill(skill_name) VALUES ('Kubernetes');
INSERT INTO skill(skill_name) VALUES ('AWS');
INSERT INTO skill(skill_name) VALUES ('GCP');
INSERT INTO skill(skill_name) VALUES ('Git');
INSERT INTO skill(skill_name) VALUES ('Jenkins');
INSERT INTO skill(skill_name) VALUES ('Agile Methodology');
INSERT INTO skill(skill_name) VALUES ('React Native');
INSERT INTO skill(skill_name) VALUES ('Flutter');
INSERT INTO skill(skill_name) VALUES ('TypeScript');
INSERT INTO skill(skill_name) VALUES ('AngularJS');
INSERT INTO skill(skill_name) VALUES ('Express.js');
INSERT INTO skill(skill_name) VALUES ('Flask');
INSERT INTO skill(skill_name) VALUES ('Django');
INSERT INTO skill(skill_name) VALUES ('Laravel');
INSERT INTO skill(skill_name) VALUES ('Ruby');
INSERT INTO skill(skill_name) VALUES ('ASP.NET');
INSERT INTO skill(skill_name) VALUES ('Unity');
INSERT INTO skill(skill_name) VALUES ('Unreal Engine');
INSERT INTO skill(skill_name) VALUES ('PostgreSQL');
INSERT INTO skill(skill_name) VALUES ('MySQL');
INSERT INTO skill(skill_name) VALUES ('MongoDB');
INSERT INTO skill(skill_name) VALUES ('Redis');
INSERT INTO skill(skill_name) VALUES ('Elasticsearch');
INSERT INTO skill(skill_name) VALUES ('GraphQL');
INSERT INTO skill(skill_name) VALUES ('Microservices');
INSERT INTO skill(skill_name) VALUES ('Serverless Architecture');
INSERT INTO skill(skill_name) VALUES ('Blockchain');
INSERT INTO skill(skill_name) VALUES ('Machine Learning');
INSERT INTO skill(skill_name) VALUES ('Deep Learning');
INSERT INTO skill(skill_name) VALUES ('NLP');
INSERT INTO skill(skill_name) VALUES ('Data Engineering');
INSERT INTO skill(skill_name) VALUES ('DevOps');
INSERT INTO skill(skill_name) VALUES ('CI/CD');
INSERT INTO skill(skill_name) VALUES ('IaC');